### PR TITLE
Footer styles to address contrast

### LINKED ISSUE #39: a11y: low contrast for some text in nav and footer
Similar to https://github.com/redwoodjs/learn.redwoodjs.com/issues/38 I noticed on the site that the contrast value for certain text in the footer and navigation is currently too low to be accessible. Generally the minimum contrast level to be accessible is 4.5:1 for AA or 3:1 for large text.

Screenshots below:

Screen Shot 2021-01-22 at 2 05 10 PM
Screen Shot 2021-01-22 at 2 04 57 PM
Screen Shot 2021-01-22 at 2 04 18 PM
Screen Shot 2021-01-22 at 2 04 10 PM

I am happy to work on updating the colors in the footer and navigation to be more accessible but am not sure in terms of branding what colors would be appropriate.

### PR DESCRIPTION
**Pull request by cannikin**
Closes #39

Let me know how this looks @M0nica!

### CODE REVIEW

**Comment by M0nica** [comment]
@cannikin This does a great job of addressing the contrast issues in the footer in both dark and light mode. I think the footer is good to go in terms of contrast after these current changes. 

https://github.com/redwoodjs/learn.redwoodjs.com/issues/39 mentioned some contrast issues outside of just the footer that persist, so I don't think the issue is fully addressed yet. When I inspected the page the text contrast is still a bit lower than 4.5 (which is generally the threshold used to determine if the color contrast is accessible for regular-sized text according to WCAG 2.0 level AA) in the top-level nav and side nav for:
- "docs" in the top-level nav (both light and dark mode) 4.34
- the active link in side bar (4.34 - light mode, 3.75 dark mode)
- the search bar text (light mode only - 2.67) 

Screen Shot 2021-01-25 at 6 24 11 PM (Image generated from https://webaim.org/resources/contrastchecker/)
Screen Shot 2021-01-25 at 6 29 15 PM

**Comment by mbush92** [comment]
@M0nica do most of the issues seem to be in dark mode?  If so, one option would be to disable the ability to switch light and dark and then the theme of this site would better match that of the main site.  @clairefro thoughts??

**Comment by clairefro** [comment]
I think we can have the best of both worlds! (dark mode + accessibility) 

We can merge this one and account for the other a11y issues in #39 separately if it is going to take some tinkering to meet the 4.5 contrast threshold elsewhere

**Comment by cannikin** [comment]
I can make the changes in this PR, no problem. Got busy today but I can work on this one tomorrow morning.

**Comment by cannikin** [comment]
Okay, more contrast updates! 

Also got the slider background on the light/dark switch. ;)

**Comment by clairefro** [comment]
this looks SO GOOD!!! Thanks to you and @M0nica for a11y-ifying 

To be persnickety while we are still in this PR, can we slap the same color for the search bar placeholder? 
image

> Also got the slider background on the light/dark switch. ;) 
Subtle touch!!

**Comment by M0nica** [comment]
Nice, it’s looking great! Thank you for making these updates.

**Comment by cannikin** [comment]
> To be persnickety while we are still in this PR, can we slap the same color for the search bar placeholder?

DONE

**Review by clairefro — APPROVED** [review]

**Pull request merged**
