### PR TITLE
Fixed link to Yarn documentation

### PR DESCRIPTION
**Pull request by ChrisLasar**
Do not merge if your project requires Yarn 1.x

### CODE REVIEW

**Comment by clairefro** [comment]
@cannikin does the tutorial require yarn 1 for any reason?

**Comment by cannikin** [comment]
Isn't yarn still on 1.x? I've got 1.22.10 locally.

**Comment by clairefro** [comment]
I'm also confused by yarn's docs. They say yarn 1.x "will reach-end-of-life soon"

image

Yet npm says latest is 1.22 🤷🏼  

image

inclined to keep it at yarn 1.x for now since that's what's been tried and true for the tutorial

**Comment by cannikin** [comment]
After some discussion it sounds like we'll be on 1.x for the foreseeable future, and we might have to switch over to something else completely (pnpm, whatever that is?). I guess Yarn 2.x doesn't play well with Redwood. :(

**Comment by ChrisLasar** [comment]
Okay. Sorry for any confusion I might have caused. Just saw this warning an thought about fixing the documentation link.

**Pull request closed without merging**
