### PR TITLE
Add colors from redwoodjs.com

### LINKED ISSUE #7: "Redwoodify" the color scheme and markdown style
The current theme colors are the default teal from Docusaurus. 
- Let's make theme colors more "Redwoody" (see below)
- Spruce (lol) up some of the drab markdown (default bland Quote block styling comes to mind)

See the [.com docs](https://redwoodjs.com/tutorial/welcome-to-redwood) for general look + feel reference (doesn't have to be a clone). 

P.S. Rob revealed some not-so-secrets about the official color scheme [here].(https://github.com/redwoodjs/learn.redwoodjs.com/issues/5#issuecomment-754919144)
image

 And [here](https://v2.docusaurus.io/docs/styling-layout) are tips on styling with Docusaurus

### PR DESCRIPTION
**Pull request by cannikin**
Got the main colors in there but I don't see an easy way to change like buttons or the footer background...I see additional variables in the web inspector, but when I try changing them nothing happens:

image

```css
/* /src/css/custom.css */

:root {
  --ifm-color-primary: #BF4722;
  --ifm-color-primary-dark: #682712;
  --ifm-color-primary-darker: #341309;
  --ifm-color-primary-darkest: #1f0a04;
  --ifm-color-primary-light: #E38163;
  --ifm-color-primary-lighter: #EBA48E;
  --ifm-color-primary-lightest: #F3C7BA;
  --ifm-code-font-size: 95%;
  --ifm-footer-background-color: #682712;
}
```

Closes #7

### CODE REVIEW

**Comment by cannikin** [comment]
Figured it out, sort of. Just overrode the footer styles directly instead of trying to be nice and set those `--ifm` vars.

**Comment by mbush92** [comment]
I was working on the same issue just now.  I have also added the following to the root class

```
	--ifm-menu-color-background-active:#FAEAE5;
	--ifm-code-background:#FAEAE5;
```

**Comment by cannikin** [comment]
Thanks @mbush92 I added those styles to this one, looks great!

image

**Review by clairefro — APPROVED** [review]
Now that's what I call Redwood!

**Pull request merged**
