### PR TITLE
Update planned release date of Redwood 1.0

### PR DESCRIPTION
**Pull request by edapm**
The release date is said to be March 2021. Have updated this to say 2022.

### CODE REVIEW

**Comment by clairefro** [comment]
@thedavidprice is early 2022 still the aim for release?

**Comment by thedavidprice** [comment]
Hi all! Yes, internally we are setting a goal for March '22. But, you know, things don't go as planned in OS all the time...

For now, I think the language we use should be either "early 2022" or even "first half of 2022".

FYI: the v1-rc release has been published and we'll be announcing officially tomorrow. So this language could be updated to say something like:
> v1 release candidate is available and the final, GA 1.0.0 release anticipated the first half of 2022

**Comment by edapm** [comment]
@thedavidprice I have updated the pages to add new information. Really excited for v1, Redwood is a great framework!

**Review by clairefro — APPROVED** [review]
Excellent! Thanks to you both. Excited about this!

**Pull request merged**
