### PR TITLE
Remove extra spaces from sample BlogPost body

### PR DESCRIPTION
**Pull request by davidlcorbitt**
Fixes this issue: [Tutorial II provides sample blog post body with extra spacing, BlogPost test fails by default](https://github.com/redwoodjs/learn.redwoodjs.com/issues/180)

This PR fixes a really minor bug, so it's not a high priority.

### CODE REVIEW

**Comment by cannikin** [comment]
Thanks for this! I remember putting those line breaks in there just so the content would look nicer in the code blocks on the site, but I may not have ever actually run the test suite again after adding them to be sure I didn't break anything! 😬 

If the test pass for you that's good enough for me! Ready to merge?

**Comment by davidlcorbitt** [comment]
Thanks for jumping on this.  Ready to merge!

**Comment by cannikin** [comment]
Here we go! The changes should be live in a couple of minutes. 

And is this really your first PR?? Congrats! 🎉

**Comment by davidlcorbitt** [comment]
It really is, thanks for such a cool experience!

**Pull request merged**
