### PR TITLE
Fix code color in dark mode

### LINKED ISSUE #24: Dark mode makes it difficult to read highlighted words
At least this is the case on my screen...
Anybody with a well calibrated screen (Apple devices?) to confirm ?

image

### PR DESCRIPTION
**Pull request by cannikin**
Closes #24

### CODE REVIEW

**Review by Thieffen — APPROVED** [review]

**Review by clairefro — CHANGES_REQUESTED** [review]
Code blocks look fantastic - can we tackle the ghostly top navbar items in dark mode while we're at it?

image

**Comment by cannikin** [comment]
Whoops! I'm on it!

**Comment by cannikin** [comment]
Okay how about THIS?

image

I'm not loving the blue-gray code background when using these new colors though...looks like the colors on the code blocks are coming from inline styles so I can't override in the stylesheet...is that something we do we converting the markdown to HTML? Where's that coming from?

**Comment by clairefro** [comment]
LOVE LOVE the redwood dark 😍  I just noticed the footer is missing out on the dark action

image

`.footer-dark` with these colors may be what you're looking for
image

**Comment by clairefro** [comment]
As to the code block styling -  it looks like under the hood docusaurus is using prism for rendering code blocks, with baked-in style:
https://github.com/facebook/docusaurus/blob/41ef333e47bd8985a6cbd82e9f2650b0fc75ec97/packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css


I haven't tested this but including something like this in the docusaurus config file might change the default theme?

```js
themeConfig: {
   prism: {
      theme: require('prism-react-renderer/themes/nightOwl')  // or any other theme
    }
}
```


That being said, the current code block thing is not HORRIBLE. 
As a last resort we could always override the existing code block styles by selecting the code block class and `important!` ing all over the place (not ideal). Here is the fun class name: 

`mdxCodeBlock_node_modules-@docusaurus-theme-classic-lib-next-theme-MDXComponents-`

**Comment by clairefro** [comment]
Huh, turns out the docusaurus config thing does work. To be honest, couldn't find one that looks good in light and dark mood. `duotoneDark` is kinda nice, but don't hate the current style either. Too bad there isn't a Red-y one 

here are some samples: 

`duotoneDark`
image

`shadesOfPurple`
image

`synthwave84`
image

**Comment by cannikin** [comment]
Okay fixed the footer!

Yeah I don't mind the code highlighting colors themselves, it's more just the blue-ish background is clashing on the dark red for me... maybe something like:

image

Mmmm chocolately.

**Review by clairefro — APPROVED** [review]

**Comment by clairefro** [comment]
LOVE dark mode and love Chocolate code blocks... feel free to toss it in if you have that code handy. 

Otherwise feel free to merge :)

**Comment by cannikin** [comment]
OKAY Got a bunch more style updates: using Open Sans to match the main site, styled blockquotes, tweaked inline code blocks, font sizes, header sizes...whew.

No idea why some elements have classes like `.navbar__title` and others are `.docTitle_node_modules-\@docusaurus-theme-classic-lib-next-theme-DocItem-`...shouldn't everything by styled with their themes? And are theme style changes actually supposed to go in `docusaurus.config.js`? But then what do they give you `custom.css` for? 

Seems much simpler to just create your own framework from scratch. ;)

**Comment by clairefro** [comment]
@cannikin  Just want to fawn over this color scheme some more - looks fantastic with the style tweaks! Thanks for taking the quote blocks from drab to fab

> Seems much simpler to just create your own framework from scratch. ;)
Spoken like a true cameronjs user

**Pull request merged**
