### PR TITLE
Make Layout ref consistent

### PR DESCRIPTION
**Pull request by nbergseng**
https://learn.redwoodjs.com/docs/tutorial/layouts/ uses `BlogLayout` for the filename and the Routes ref, and later steps swap it to `BlogPostLayout`.

### CODE REVIEW

**Comment by clairefro** [comment]
@cannikin can you confirm this?

**Comment by cannikin** [comment]
Yep that fix looks correct, not sure when that filename changed...maybe something to do with updating the docs for the new `<Set>` stuff?

**Comment by clairefro** [comment]
Which way are we going to go? Shall we merge this change and add your latest suggestion separately?

**Comment by clairefro** [comment]
Any word on a direction for this?

**Comment by cannikin** [comment]
I want to keep it `BlogLayout` as it’s the layout for “the blog” not just an individual a post. 

I thought I saw someone update the Routes to use `<Set>` and add the layout in there as a `wrap` already? Maybe I dreamed that…

**Comment by clairefro** [comment]
closing as we decided to keep as-is

**Pull request closed without merging**
